name: Dev Docker Publish

concurrency:
  group: docker-dev
  cancel-in-progress: true

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    - cron: "0 2 * * *" # run at 2 AM UTC

  push:
    branches:
      - master

jobs:
  docker:
    uses: ./.github/workflows/docker-publish.yml
    with:
      tags: ulisesjeremias/vsl:dev
      build-args: |
        DEV_IMG=true
